[colors.primary]
background = "#242626"
foreground = "#99a3a2"
dim_foreground = "#8087a2"
bright_foreground = "#cad3f5"

[colors.cursor]
text = "#24273a"
cursor = "#d1dfde"

[colors.vi_mode_cursor]
text = "#24273a"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#24273a"
background = "#a5adcb"

[colors.search.focused_match]
foreground = "#24273a"
background = "#a6da95"

[colors.footer_bar]
foreground = "#24273a"
background = "#a5adcb"

[colors.hints.start]
foreground = "#24273a"
background = "#eed49f"

[colors.hints.end]
foreground = "#24273a"
background = "#a5adcb"

[colors.selection]
text = "#242626"
background = "#7f8786"

[colors.normal]
black = "#000000"
red = "#666c6b"
green = "#a16869"
yellow = "#dc5b5f"
blue = "#99a569"
magenta = "#bfde54"
cyan = "#a29069"
white = "#deb35f"

[colors.bright]
black = "#6a8fa3"
red = "#62b1df"
green = "#6971a3"
yellow = "#6ba48f"
blue = "#64e39c"
magenta = "#5f6ede"
cyan = "#d1dfde"
white = "#99a3a2"

[colors.dim]
black = "#494d64"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5bde6"
cyan = "#8bd5ca"
white = "#b8c0e0"

#[[colors.indexed_colors]]
#index = 16
#color = "#f5a97f"

#[[colors.indexed_colors]]
#index = 17
#color = "#f4dbd6"

